HH-118206 add dynamic weight update
hhru/nuts-and-bolts pull request #281
Opened 2020-11-24 13:44 UTC by dzharikhin

2020-11-24 13:48 UTC, dzharikhin commented on nab-tests/src/test/java/ru/hh/nab/starter/NabAppTestConfig.java
> +    when(mock.getConfig()).thenReturn(new ClientConfig());
вот эта штука умеет watchSeconds сразу для всех кешей. наверное лучше сразу индивидуальные крутилки

2020-11-24 15:51 UTC, heruv1m commented on nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
> +  public static final String CONSUL_KV_CACHE_CONSISTENCY_MODE_PROPERTY = "consul.weightCache.consistencyMode";
вот для этого я бы сразу конфиги выпустил в ддс

2020-11-24 16:03 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
> +        //first cache init
ну по логике должно выстрелить. ты регаешься, запускаешь кеш и сразу же регаешься еще раз

2020-11-24 16:03 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
> +      registerWithWeight(weight);
ну с тем, что сконфигурен

2020-11-24 16:04 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
> +  public static final String CONSUL_KV_CACHE_CONSISTENCY_MODE_PROPERTY = "consul.weightCache.consistencyMode";
какие? в смысле, чтобы сразу прописать stale?

2020-11-25 08:10 UTC, heruv1m commented on nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
> +  public static final String CONSUL_KV_CACHE_CONSISTENCY_MODE_PROPERTY = "consul.weightCache.consistencyMode";
угу

2020-11-25 09:56 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
> +        //first cache init
эх, оно не сработает(

2020-11-25 13:26 UTC, heruv1m approved these changes

2020-11-25 13:28 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/ConsulService.java
> +  public static final String CONSUL_KV_CACHE_CONSISTENCY_MODE_PROPERTY = "consul.weightCache.consistencyMode";
тут вроде тоже закрыли - прописать можно будет общий consul.consistencyMode

2020-11-27 12:22 UTC, heruv1m requested changes

2020-11-27 12:22 UTC, heruv1m commented on nab-example/src/main/java/ru/hh/nab/example/ExampleMain.java
> +    System.setProperty(NabProdConfig.CONSUL_PORT_PROPERTY, String.valueOf(consulPort));
не проклянут ли нас потомки за этот ходом конем.

2020-11-27 12:22 UTC, heruv1m commented on nab-starter/src/main/java/ru/hh/nab/starter/NabCommonConfig.java
> +  String nodeName(FileSettings fileSettings) {
я что то не вижу использований

2020-11-27 12:34 UTC, dzharikhin commented on nab-example/src/main/java/ru/hh/nab/example/ExampleMain.java
> +    System.setProperty(NabProdConfig.CONSUL_PORT_PROPERTY, String.valueOf(consulPort));
да не должны по идее. это ж в example

2020-11-27 12:37 UTC, heruv1m approved these changes

2020-11-27 13:25 UTC, merged