HH-121275 move test loggins into logback configurator + small build log cleanup
hhru/nuts-and-bolts pull request #286
Opened 2020-12-13 19:37 UTC by SCREEN88

https://jira.hh.ru/browse/HH-121275

2020-12-13 19:59 UTC, SCREEN88 commented on .gitignore
> +logs
логи в течении прогона тестов пишутся в эту директорию, подробнее ниже

2020-12-13 19:59 UTC, SCREEN88 commented on nab-example/pom.xml
> +                    <disableXmlReport>true</disableXmlReport>
эти опции позволяют не выводить данные которые пишутся в консоль в течении прогона пишутся в указанную директорию в отдельный файл для каждого теста, в xml в основном писались данные теста параметры, системные переменные, вообщем не увидел ничего интересного, отключил.
!стектрейс и причина падения теста продолжают писаться в консоль с этими параметрами!

2020-12-13 19:59 UTC, SCREEN88 commented on nab-logging/src/main/java/ru/hh/nab/logging/HhMultiAppender.java
> +  public HhMultiAppender(boolean json, boolean logToConsole) {
мне нужно было чтобы аппендер мог писать в файл даже с включенным проперти LOG_TO_CONSOLE_PROPERTY_KEY, ничего лучше не придумал, чтобы не пришлось во всех проектах править (

2020-12-13 19:59 UTC, SCREEN88 commented on nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
> +  protected void statusListener(LoggerContext context, Properties properties) {
чтобы можно было отключать StatusListener для тестов, Properties передаю чтобы можно было это конфигурировать

2020-12-13 19:59 UTC, SCREEN88 commented on nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
> +  public LoggerWrapper createLogger(LoggingContextWrapper context, String name, ch.qos.logback.classic.Level level, boolean additivity,
добавил ch.qos.logback.classic.Level потому-что в spy нет Level.OFF

2020-12-13 19:59 UTC, SCREEN88 commented on nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
> +    public void detachAppenders(Appender... appenders) {
иногда удобно вытащить логгер, удалить аппендер и добавить свой, чтобы не переопределять лишний раз

2020-12-13 19:59 UTC, SCREEN88 commented on nab-starter/src/test/java/ru/hh/nab/starter/NabStarterTestLogbackBaseConfigurator.java
> +public class NabStarterTestLogbackBaseConfigurator extends NabLoggingConfiguratorTemplate {
удалил тут logback.xml, добавил примитивный Configurator, из testCaseBase подтянуть нельзя

2020-12-13 19:59 UTC, SCREEN88 commented on nab-testbase/src/main/java/ru/hh/nab/testbase/TestLogbackBaseConfigurator.java
> +      appenders.add(createAppender(context, logFileName, () -> new HhMultiAppender(false, false)));
кажется что может быть иногда полезно писать весь лог в один файл

2020-12-13 19:59 UTC, SCREEN88 commented on nab-testbase/src/main/java/ru/hh/nab/testbase/TestLogbackBaseConfigurator.java
> +      put("org.testcontainers.utility.ResourceReaper", Level.OFF);
взял какие-то базовые вещи, обсуждаемо

2020-12-13 19:59 UTC, SCREEN88 commented on nab-tests/pom.xml
> +            </plugin>
при попытке собрать jar из nab-test писался варнинг что файлов то нет, таким образом исключаю попытку создания

2020-12-13 19:59 UTC, SCREEN88 commented on pom.xml
> +        </pluginManagement>
добавил сюда пока, как можно будет поднять public-pom можно убрать

2020-12-13 20:02 UTC, SCREEN88 commented
еще остался файл shared-pattern-logback.xml, который по факту больше не нужен, могу тоже удалить

2020-12-15 10:05 UTC, heruv1m approved these changes

2020-12-15 10:19 UTC, heruv1m commented on pom.xml
> +        </pluginManagement>
а не поднял из за 15-й джавы?

2020-12-15 10:20 UTC, heruv1m approved these changes

2020-12-15 10:25 UTC, SCREEN88 commented on pom.xml
> +        </pluginManagement>
угу

2020-12-15 11:04 UTC, heruv1m approved these changes

2020-12-15 11:20 UTC, heruv1m requested changes

2020-12-15 11:20 UTC, heruv1m commented on pom.xml
> +        </pluginManagement>
давай лучше поднимем в комон поме, а тут перезапишем версию жабы

2020-12-15 11:24 UTC, SCREEN88 commented on pom.xml
> +        </pluginManagement>
можно и так, а там больше ничего нет критичного?

2020-12-15 12:31 UTC, dzharikhin requested changes

2020-12-15 12:31 UTC, dzharikhin commented on nab-example/pom.xml
> +                    <disableXmlReport>true</disableXmlReport>
а почему не в /target/logs

2020-12-15 12:31 UTC, dzharikhin commented on nab-logging/src/main/java/ru/hh/nab/logging/HhMultiAppender.java
> +  public HhMultiAppender(boolean json, boolean logToConsole) {
расскажи чуть больше. из кода восстановить не могу

2020-12-15 12:31 UTC, dzharikhin commented on nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
> +    public void detachAppenders(Appender... appenders) {
зачем варарг? ну коллекцию и передавай

2020-12-15 12:31 UTC, dzharikhin commented on nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
> +  public LoggerWrapper createLogger(LoggingContextWrapper context, String name, ch.qos.logback.classic.Level level, boolean additivity,
мы не торчим им наружу - это реализация. можем торчать только api

2020-12-15 12:35 UTC, dzharikhin commented on nab-testbase/src/main/java/ru/hh/nab/testbase/TestLogbackBaseConfigurator.java
> +      throw new UncheckedIOException(e);
повышенная елочность. может как-то все в один try с логированием и new Properties() если что-то идет не так?

2020-12-15 12:43 UTC, SCREEN88 commented on nab-example/pom.xml
> +                    <disableXmlReport>true</disableXmlReport>
мы обычно отдельно папку с логами держим. Если добавить в /target/logs то при mvn clear она будет удаляться, или ты этого и хочешь?

2020-12-15 12:46 UTC, SCREEN88 commented on nab-logging/src/main/java/ru/hh/nab/logging/HhMultiAppender.java
> +  public HhMultiAppender(boolean json, boolean logToConsole) {
если вот тут https://github.com/hhru/nuts-and-bolts/pull/286/files#diff-576068c88458d107c252cf9fea0f4a3494ae55dea0226ddff47420cb345c9ce7L78  прилетит true, то мы всегда будем возвращать только ConsoleAppender

2020-12-15 12:46 UTC, SCREEN88 commented on nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
> +  public LoggerWrapper createLogger(LoggingContextWrapper context, String name, ch.qos.logback.classic.Level level, boolean additivity,
не понял (

2020-12-15 12:47 UTC, SCREEN88 commented on nab-logging/src/main/java/ru/hh/nab/logging/NabLoggingConfiguratorTemplate.java
> +    public void detachAppenders(Appender... appenders) {
ок

2020-12-15 12:48 UTC, SCREEN88 commented on nab-testbase/src/main/java/ru/hh/nab/testbase/TestLogbackBaseConfigurator.java
> +      throw new UncheckedIOException(e);
тогда придется добавить два catch, один для NullPointerException, второй IOException, объединить их не получиться

2020-12-15 12:48 UTC, SCREEN88 commented on pom.xml
> +        </pluginManagement>
поправил

2020-12-15 15:47 UTC, dzharikhin approved these changes
пару мест кажется можно отревертить, апрувлю

2020-12-15 15:47 UTC, dzharikhin commented on .gitignore
> +logs
не нужно больше

2020-12-15 15:47 UTC, dzharikhin commented on nab-logging/src/main/java/ru/hh/nab/logging/HhMultiAppender.java
> +  public HhMultiAppender() {
тут кажется только отступы перекладывания

2020-12-16 08:57 UTC, heruv1m approved these changes

2020-12-16 15:46 UTC, merged