HH-127076 move DoubleStorageCache to nab
hhru/nuts-and-bolts pull request #314
Opened 2021-04-05 11:16 UTC by Afftobus

задача https://jira.hh.ru/browse/HH-127076

2021-04-06 15:27 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +  private final int defaultMaxCollectionSize = 256;
статик?

2021-04-06 15:31 UTC, Afftobus commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +  private final int defaultMaxCollectionSize = 256;
ну да, конечно )

2021-04-06 15:38 UTC, dzharikhin requested changes

2021-04-06 15:38 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/DoubleStorageCache.java
> +//    Тут наивная имплементация, есть место для гонок, однако оставлем в таком виде потому что
зачем нужен этот коммент?

2021-04-06 15:38 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/DoubleStorageCache.java
> +public class DoubleStorageCache<K, V> {
название неподходящее - я ожидал увидеть тут Double тип
это скорее какой-то PartiallyOverflowingCache
и вроде ничего про jersey тут нет - его бы наверное в common модуль переложить
вообще, конечно, херь адская

2021-04-06 15:38 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +          LOGGER.warn("Size of collection legacyJaxbContexts exceeds {} and equals {}",
ты хочешь на каждую сериализацию писать WARN - не надо так.
если хочешь, чтобы это как-то можно было диагностировать, то надо тут метрики прикрутить и слать размер периодически

2021-04-06 16:06 UTC, kincajou commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/DoubleStorageCache.java
> +//    Тут наивная имплементация, есть место для гонок, однако оставлем в таком виде потому что
я просил, чтобы тот кто полезет "оптимизировать" сначала подумал

2021-04-06 16:08 UTC, kincajou commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +          LOGGER.warn("Size of collection legacyJaxbContexts exceeds {} and equals {}",
идея была такая - это произойдет примерно никогда, но когда произойдет - пусть засрет всю сентри, авось ктонить заметит
метрики если не прикручивать то никто не заметит
но варн помоему в сентри не попадет

2021-04-06 16:09 UTC, kincajou commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +          LOGGER.warn("Size of collection legacyJaxbContexts exceeds {} and equals {}",
ну и тут уже не "legacy"

2021-04-06 16:31 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/DoubleStorageCache.java
> +//    Тут наивная имплементация, есть место для гонок, однако оставлем в таком виде потому что
ну давайте как-то покороче, чем на 10 строчек

2021-04-06 16:34 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +          LOGGER.warn("Size of collection legacyJaxbContexts exceeds {} and equals {}",
В сентри варн не попадет
но даже если и еррор. никто не смотрит в логи или сентри настолько оперативно, чтобы не допустить адского спама в логи этим сообщением 
поэтому если в лог писать такое, то по-любому нужен какой-то тротлинг здесь. раз в минуту там писать или еще как

2021-04-06 16:40 UTC, kincajou commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/DoubleStorageCache.java
> +//    Тут наивная имплементация, есть место для гонок, однако оставлем в таком виде потому что
не вижу проблемы, норм описание, Артем написал jmh тесты, тут результаты коротко, зачем на строчках экономить?

2021-04-06 17:03 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/DoubleStorageCache.java
> +//    Тут наивная имплементация, есть место для гонок, однако оставлем в таком виде потому что
Затем, что они не несут никакой пользы.
Если мне завтра покажется код неоптимальным, то я из этого коммента не сделаю вывод, что не надо его тюнить. Что может быть более полезным в этом плане - выложить jmh test'ы и жавадокой тут оставить на них линку - тогда кто полезет тюнить - сможет увидеть какие кейсы пробовали и убедиться, что уже потюнено, мб в жаве 19 оптимальнее будет другой способ какой-то

2021-04-06 19:23 UTC, kincajou commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/DoubleStorageCache.java
> +//    Тут наивная имплементация, есть место для гонок, однако оставлем в таком виде потому что
польза в том чтобы люди не пытались оптимизировать то что уже попробовали и оказалось бесполезным
изначально я предлагал код посложнее но после бенчей оказалось что нафик не нужно

а длинный коммент не мешает и вреда не несет

jmh можно линкануть, да

2021-04-07 15:25 UTC, dzharikhin commented on nab-common/src/main/java/ru/hh/nab/common/cache/PartiallyOverflowingCache.java
> +   * jmh test https://github.com/Afftobus/jmh-benchmark
давай сюда свои тесты приноси, хитренький) сложи в отдельную папочку в тестах

2021-04-07 15:25 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +        sender.sendMax(cacheSizeMetricName, cacheSize)
здесь бы наверное или слать процент заполнения
или 2 метрики - максимальный размер по настройкам + текущий размер

2021-04-07 15:42 UTC, Afftobus commented on nab-common/src/main/java/ru/hh/nab/common/cache/PartiallyOverflowingCache.java
> +   * jmh test https://github.com/Afftobus/jmh-benchmark
jmh тесты в наб тащить О_о?

2021-04-07 15:47 UTC, dzharikhin commented on nab-common/src/main/java/ru/hh/nab/common/cache/PartiallyOverflowingCache.java
> +   * jmh test https://github.com/Afftobus/jmh-benchmark
ну ты набовский компонент тюнишь, пишешь что тюнинг покрыт jmh тестами. почему тесты по которым этот тюнинг сделан должны лежать в чьей-то личной репе?

2021-04-07 18:26 UTC, dzharikhin commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +          sender.sendMax(cacheSizeMetricName, cacheMaxSize);
во-первых, если я все правильно понимаю, шлешь метрику с тем же именем
во-вторых, вроде Max очищается при отправке вроде, да и нужен ли здесь max?

2021-04-07 18:27 UTC, dzharikhin commented on nab-tests/pom.xml
> +                    <excludes>ru/hh/nab/performance/generated/*</excludes>
эмм.. а почему мы не проверяем на чекстайл тесты?

2021-04-07 18:28 UTC, Afftobus commented on nab-tests/pom.xml
> +                    <excludes>ru/hh/nab/performance/generated/*</excludes>
там автоматически генерится дофига всего, что чекстайл не пропускает.

2021-04-07 18:28 UTC, Afftobus commented on nab-starter/src/main/java/ru/hh/nab/starter/jersey/MarshallerContextResolver.java
> +          sender.sendMax(cacheSizeMetricName, cacheMaxSize);
вот хотел потестить, как это будет работать.

2021-04-08 10:07 UTC, dzharikhin approved these changes

2021-04-09 09:41 UTC, merged