HH-145226 Add telemetry to kafka
hhru/nuts-and-bolts pull request #356
Opened 2022-02-09 09:00 UTC by Aulust

2022-02-09 13:49 UTC, pvorlov requested changes

2022-02-09 13:49 UTC, pvorlov commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
> +        (String) configProvider.getConsumerConfig(topicName).get(CLIENT_ID_CONFIG), topicName, operationName);
Зачем? Сейчас практически никто не проставляет client.id в конфигах.

2022-02-09 13:49 UTC, pvorlov commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
> +  private Span startSpan(List<ConsumerRecord<String, T>> messages) {
Отсюда тоже можно всё это унести, аналогично как написал для producer'ов

2022-02-09 13:49 UTC, pvorlov commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
> +        if (processedMessages.size() <= 40) {
Почему понадобилось изменение?

2022-02-09 13:51 UTC, Aulust commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
> +        (String) configProvider.getConsumerConfig(topicName).get(CLIENT_ID_CONFIG), topicName, operationName);
Во всех конфигах сейчас client.id есть. У тебя получается конфликт - что в конфиге указано одно и оно попадет в getConsumerConfig, а в ConsumerGroupId - другое

2022-02-09 13:52 UTC, Aulust commented on nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
> +    ProducerRecord<String, Object> producerRecord = new ProducerRecord<>(topicName, key, kafkaMessage);
вот я не хотел такое делать - становится слишком вербозно, притом что телеметрия по идее у нас будет везде. Ну навено сделать можно в теории

2022-02-09 13:58 UTC, pvorlov commented on nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
> +    ProducerRecord<String, Object> producerRecord = new ProducerRecord<>(topicName, key, kafkaMessage);
Вербозно как раз сейчас, класс очень большой. Даже если захотите потом nab-telemetry вмёржить в starter - разнесение на уровне пакетов упростит код.

2022-02-09 13:59 UTC, pvorlov commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerFactory.java
> +        (String) configProvider.getConsumerConfig(topicName).get(CLIENT_ID_CONFIG), topicName, operationName);
во всех есть для producer'а. Для consumer'а только для api webhook нашёл.
Ну впринципе ок, если оно фоллбечится на service_name

2022-02-09 14:00 UTC, pvorlov commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerGroupId.java
> +  private final String clientId;
Ниже обсудили

2022-02-14 11:01 UTC, heruv1m commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
> +      builder.addLink(Span.fromContext(extractedContext).getSpanContext());
я не понял как это будет работать. Разве не будут спаны разных запросов привязываться к текущему?

2022-02-14 11:03 UTC, heruv1m commented on nab-kafka/src/main/java/ru/hh/nab/kafka/producer/DefaultKafkaProducer.java
> +    ProducerRecord<String, Object> producerRecord = new ProducerRecord<>(topicName, key, kafkaMessage);
я ЗА вынос кода телеметрии из кафка продюсера. На счет отдельного модуля я бы подумал стоит ли

2022-02-16 11:35 UTC, Aulust commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
> +        if (processedMessages.size() <= 40) {
это чинит тест падающий, он меня достал

2022-02-16 11:42 UTC, heruv1m commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
> +        if (processedMessages.size() <= 40) {
может отключить тогда? Я так понимаю он уже не проверяет ничего в таком виде?

2022-02-16 11:47 UTC, Aulust commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRecoveryAfterFailTest.java
> +        if (processedMessages.size() <= 40) {
проверяет частично, но по-хорошему нужно его конечно будет переписать как-то потом

2022-02-16 15:55 UTC, pvorlov approved these changes

2022-02-17 16:40 UTC, merged