HH-177707 add otel.status_description
hhru/nuts-and-bolts pull request #402
Opened 2023-04-14 14:36 UTC by heruv1m

2023-04-14 14:37 UTC, heruv1m commented on nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
> +    span.setStatus(otelStatus, StatusCode.ERROR == otelStatus ? response.getStatusText() : "");
хорошие ответы нам не нужны

2023-04-14 14:55 UTC, pvorlov requested changes

2023-04-14 14:55 UTC, pvorlov commented on nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
> +    span.setStatus(otelStatus, StatusCode.ERROR == otelStatus ? response.getStatusText() : "");
Погоди, а питон также работает?
В одно поле миксует и текст и статус?
Если это ""http.status_code" то у нас platform-supervisor не может правильно работать, т.к. пробует кастануть эту цифру к инту.
А почему мы не хотим разделить? Код ошибки один атрибут а сообщение об ошибке другой?

2023-04-14 15:04 UTC, heruv1m commented on nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
> +    span.setStatus(otelStatus, StatusCode.ERROR == otelStatus ? response.getStatusText() : "");
телеметрия их потом под капотом рассовывает по полям. Но че то не нашел где

2023-04-14 15:39 UTC, pvorlov commented on nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
> +    span.setStatus(otelStatus, StatusCode.ERROR == otelStatus ? response.getStatusText() : "");
Я не буду по исходникам лазить сейчас :)
Мой посыл, что надо удостовериться что у нас http.status_code это железобетонно число и в джава и в питоне

2023-04-17 08:52 UTC, heruv1m commented on nab-telemetry/src/main/java/ru/hh/nab/telemetry/TelemetryListenerImpl.java
> +    span.setStatus(otelStatus, StatusCode.ERROR == otelStatus ? response.getStatusText() : "");
[хттп статус я не трогаю](https://github.com/hhru/nuts-and-bolts/pull/402/files#diff-c5bd0a79a618f81f26400aaa1db50bb24cfb29302232eea5bc76a690cfc69503L82)

2023-04-17 10:00 UTC, pvorlov approved these changes

2023-04-17 10:18 UTC, merged