HH-188149 add opportunity to switch between different databases + refactoring
hhru/nuts-and-bolts pull request #419
Opened 2023-08-07 15:01 UTC by rogoza-igor

2023-08-08 08:15 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/healthcheck/HealthCheck.java
> +  public abstract Result check();
Этот метод имеет модификатор protected в `com.codahale.metrics.health.HealthCheck`, из за чего не мог к нему обратиться в RoutingDataSource. Пришлось унаследоваться, чтоб расширить до public

2023-08-08 08:16 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +  private final Map<String, LazyConnectionDataSource> targetDataSources = new HashMap<>();
Раньше в LazyConnectionDataSource оборачивался только тот датасорс, который передавался в конструктор. Теперь все датасорсы оборачиваются в LazyConnectionDataSource

2023-08-08 08:20 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +  @Deprecated(forRemoval = true)
Раньше в конструктор передавался дефолтный датасорс, на который делался фоллбэк в случае, если какой то датасорс не был найден. Но мы уже давно выпилили логику фоллбэка, и не совсем понятно, что есть дефолтный датасорс. Поэтому предлагаю вообще не передавать никакие датасорсы через конструктор, и добавлять их с помощью методов addDataSource / addNamedDataSource

2023-08-08 08:25 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +      throw new IllegalStateException("DataSource passing via RoutingDataSource constructor is not supported " +
Нельзя использовать этот конструктор, когда сервис работает с несколькими базами, потому что для переданного в конструкторе датасорса используется имя DataSourceType.MASTER, и оно не будет совпадать с настоящим именем датасорса (имя базы + тип). Ну и уже писал, что предлагаю считать этот конструктор deprecated)

2023-08-08 08:27 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +                  .orElseThrow(() -> new IllegalStateException("Secondary datasource %s is not configured".formatted(secondaryDataSourceName)));
Тут раньше вообще бага была, потому что если среди реплик не находили secondaryDataSource, указанный в конфиге, то делался фоллбэк на мастер. А мы как раз уходили от всяких неявных фоллбэков

2023-08-09 15:27 UTC, pvorlov requested changes
Что понравилось:
1. Возможность динамически переключаться через supplier
2. Упрощение кода RoutingDataSource из-за отсутствия дефолтов
3. Наведение порядка со стораджами
4. Наведение порядка с Hikari

Неоднозначно:
Выпиливание дефолтовых датасорсов.
Непонятно как при этом должен работать transactional если нет дефолта?

Что не понравилось:
1. Добавление кронового типа. Хардкод датасорсов это легаси для обратной совместимости
2. Lazy на все датасорсы, уместнее при таком подходе наоборот убрать со всего lazy
3. Логика завязанная на формат строки и множественные конкатенации в рантайме
4. Что supplier используется в сервисе перед настройкой. Это торчащие наружу кишочки. Мне кажется правильнее было бы передавать supplier как консруктор RoutingDataSource

2023-08-10 12:04 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceType.java
> +  public static final String CRON_MASTER = "cronMaster";
Ревертнул https://github.com/hhru/nuts-and-bolts/pull/419/commits/a5a736a7a6a16bbf062ee413ca0587d476e71feb

2023-08-10 12:04 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceSettings.java
> +  public  static final String DATASOURCE_NAME_FORMAT = "%s.%s";
Поправил https://github.com/hhru/nuts-and-bolts/pull/419/commits/5096210fbed11b741e295304bfa8798b3f75d87d

2023-08-10 12:05 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +  private final Map<String, LazyConnectionDataSource> targetDataSources = new HashMap<>();
Выпилил оборачивание в lazy для всех датасорсов https://github.com/hhru/nuts-and-bolts/pull/419/commits/82f7c5924266fbee1a87b4bdbcadf7220b88cd96

2023-08-10 12:07 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +   * @deprecated Use {@link RoutingDataSourceFactory#create()} and add all dataSources via
Я поправил комменты + выпилил @Deprecated, потому что в целом можно мастер и через конструктор передавать, как раньше, если не нужно работать с несколькими базами https://github.com/hhru/nuts-and-bolts/pull/419/commits/1da0af8e33d6dde94e430d727bb78f10d5425682

2023-08-10 12:08 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafe.java
> +    return databaseNameSupplier == null ? dataSourceType : DATASOURCE_NAME_FORMAT.formatted(databaseNameSupplier.get(), dataSourceType);
Добавил DatabaseManager (название обсуждаемо. мне просто показалось, что switcher не совсем правильное для него название)
https://github.com/hhru/nuts-and-bolts/pull/419/commits/3e266f5e3f22ff1b68f9cf5b911374a4caaca79c - тут перенес DataSourceContextUnsafe в модуль nab-data-source
https://github.com/hhru/nuts-and-bolts/pull/419/commits/e9742d737b6c90d1f26ab4914f4f6b3180529214 - а тут уже основные изменения

2023-08-10 12:10 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafe.java
> +    return ofNullable(currentDataSourceName.get()).orElseGet(() -> createDataSourceName(DataSourceType.MASTER));
Договорились, что это норм. Если не заинжектить мастер в RoutingDataSource, будет стрелять ошибка с понятным текстом

2023-08-10 12:11 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +    Map<String, HealthCheck> dataSourceHealthChecks = targetDataSources.values().stream()
Поправил https://github.com/hhru/nuts-and-bolts/pull/419/commits/b46064f787a28cfad2587dfafcbf33c331287544

2023-08-10 12:12 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +   * @deprecated Use {@link RoutingDataSourceFactory#create()} and add all dataSources via
Я думаю в целом не очень хорошо давать линки на фабрику в RoutingDataSource, так как он про фабрику вообще ничего не должен знать

2023-08-10 12:14 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafe.java
> +    return databaseNameSupplier == null ? dataSourceType : DATASOURCE_NAME_FORMAT.formatted(databaseNameSupplier.get(), dataSourceType);
таких [хаков](https://github.com/hhru/nuts-and-bolts/commit/e9742d737b6c90d1f26ab4914f4f6b3180529214#diff-440853cb40432ee93c9feb6c18e42f1d53ba4c07583d737b2c8d15b1eeceeb72R16) мне еще не доводилось делать)

2023-08-10 12:16 UTC, rogoza-igor commented
Я там еще поправил немного описание того, что нужно сделать в коде сервиса, чтоб все заработало

2023-08-10 12:48 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseManager.java
> +  private final ConcurrentMap<String, ConcurrentMap<String, String>> dataSourceNames = new ConcurrentHashMap<>();
ConcurrentHashMap тяжёлая и будет использовать потокобезопасные конструкции при каждом чтении.
Мы записывать в неё будем на старте а потом записи быть не должно.
Может вместо неё обычную иммутабельную мапу и volatile переменную?
Перестраивать при каждой регистрации на новую.
Должно работать быстрее.

2023-08-10 12:48 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceFactory.java
> +  ) {
Разве Spring не требует чтобы был единственый конструктор у бина или анотация?

2023-08-10 12:48 UTC, pvorlov commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafe.java
> +    return databaseNameSupplier == null ? dataSourceType : DATASOURCE_NAME_FORMAT.formatted(databaseNameSupplier.get(), dataSourceType);
Мне не очень нравится название.
'DatabaseManager' звучит как нечто, что должно быть в каждом сервисе использующем базу. Хотя по факту его ответственность переключаться между базами.
Хочется чтобы его специцика отображалась в названии.
А что тебе не понравилось в Switcher?

2023-08-10 12:49 UTC, pvorlov commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/datasource/RoutingDataSource.java
> +    Map<String, HealthCheck> dataSourceHealthChecks = targetDataSources.values().stream()
Всё ещё не по стайлгайду :)
чейнится включая первый методо
```
dataSourceHealthChecks.
  .keySet()
  .stream()
...
```

2023-08-10 13:01 UTC, rogoza-igor commented on nab-hibernate/src/main/java/ru/hh/nab/hibernate/transaction/DataSourceContextUnsafe.java
> +    return databaseNameSupplier == null ? dataSourceType : DATASOURCE_NAME_FORMAT.formatted(databaseNameSupplier.get(), dataSourceType);
Переименовал https://github.com/hhru/nuts-and-bolts/pull/419/commits/1cfbf0ad0cd5b0caf61960598d01b5021cc9a0ee

2023-08-10 13:04 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourceFactory.java
> +  ) {
Требует. Но мы сами [создаем инстанс DataSourceFactory](https://github.com/hhru/nuts-and-bolts/blob/1cfbf0ad0cd5b0caf61960598d01b5021cc9a0ee/nab-data-source/src/main/java/ru/hh/nab/datasource/NabDataSourceProdConfig.java#L22). Поэтому не стал добавлять аннотацию

2023-08-10 13:10 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseManager.java
> +  private final ConcurrentMap<String, ConcurrentMap<String, String>> dataSourceNames = new ConcurrentHashMap<>();
Я на самом деле подсмотрел в [DataSourcePropertiesStorage](https://github.com/hhru/nuts-and-bolts/blob/de8f4c0668762f44c0a0e25626127c3cb0eada71/nab-data-source/src/main/java/ru/hh/nab/datasource/DataSourcePropertiesStorage.java#L9), там тоже ConcurrentMap юзается. Блин а вот запись в эти мапы может вообще из разных потоков осуществляться?

2023-08-10 13:19 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseManager.java
> +  private final ConcurrentMap<String, ConcurrentMap<String, String>> dataSourceNames = new ConcurrentHashMap<>();
> volatile тут не поможет, он только ссылку будет в актуальном состоянии поддерживать

Этого и достаточно если мапа будет иммутабельна

> в эти мапы может вообще из разных потоков осуществляться?

Скорее всего нет. Но вот чтение может и тут уже нет гарантий что они увидят, что записалось

2023-08-11 06:57 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +  private volatile Map<String, Map<String, String>> dataSourceNamesForRead;
оба volatil'а уже не нужно добавлять если есть suncronized. Из обычной переменной будет быстрее чтение.

2023-08-11 06:57 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +        .collect(Collectors.toMap(Map.Entry::getKey, entry -> new HashMap<>(entry.getValue())));
Collectors.toMap

There are no guarantees on the type, mutability, serializability, or thread-safety of the Map returned.

2023-08-11 07:43 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +  private volatile Map<String, Map<String, String>> dataSourceNamesForRead;
Сравнение ссылок в методе `getDataSourceNames` делается не в блоке synchronized

2023-08-11 07:46 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +        .collect(Collectors.toMap(Map.Entry::getKey, entry -> new HashMap<>(entry.getValue())));
```
return new CollectorImpl<>(HashMap::new,
                                   uniqKeysMapAccumulator(keyMapper, valueMapper),
                                   uniqKeysMapMerger(),
                                   CH_ID);
```

2023-08-11 07:52 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +  private volatile Map<String, Map<String, String>> dataSourceNamesForRead;
Да, тогда лучше сделать проверку `dataSourceNamesForRead == null`.

Нет никакакого смысла делать 2 коллекции если есть volatile. С volatile достаточно одной.

2023-08-11 07:53 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +        .collect(Collectors.toMap(Map.Entry::getKey, entry -> new HashMap<>(entry.getValue())));
В этой версии джава так, в следующей по другому. Нельзя на это полагаться.

2023-08-11 07:54 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +        .collect(Collectors.toMap(Map.Entry::getKey, entry -> new HashMap<>(entry.getValue())));
Ну камон, если в следующей версии джава toMap будет возвращать mutable мапу, тогда будет миллион мест в коде, где все взорвется)

2023-08-11 07:56 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +  private volatile Map<String, Map<String, String>> dataSourceNamesForRead;
> Надо комментарий оставить что оптимизаця работает только в случае гипотезы что есть гарантия, что все чтения будут после записи

Я хотел сделать так, чтоб мы не полагались на эту гипотезу

2023-08-11 08:03 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +        .collect(Collectors.toMap(Map.Entry::getKey, entry -> new HashMap<>(entry.getValue())));
Указал явно тип мапы https://github.com/hhru/nuts-and-bolts/pull/419/commits/22091e26cf71aff66a08974cff96ff6324db440b

2023-08-11 08:09 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +        .collect(Collectors.toMap(Map.Entry::getKey, entry -> new HashMap<>(entry.getValue())));
Взорвётся только у сам-себе-злобных-буратин.
Я нигде не полагался на мутабельность.

В чём проблема указать явно?
` .collect(
    Collectors.toMap(
      Map.Entry::getKey,
      entry -> new HashMap<>(entry.getValue(),
      (key1, key2) -> key1,
      HashMap::new
    )
  )
);`

2023-08-11 08:12 UTC, pvorlov commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +  private volatile Map<String, Map<String, String>> dataSourceNamesForRead;
Если мы на неё не полагаемся то оптимизация с двумя мапами не сработает

2023-08-11 08:14 UTC, rogoza-igor commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +  private volatile Map<String, Map<String, String>> dataSourceNamesForRead;
Почему?

2023-08-11 08:38 UTC, pvorlov approved these changes

2023-08-11 14:31 UTC, pvorlov approved these changes

2023-08-11 14:55 UTC, merged

2023-08-14 08:13 UTC, vbazhmin commented on nab-data-source/src/main/java/ru/hh/nab/datasource/DatabaseSwitcher.java
> +    DataSourceContextUnsafe.setDatabaseSwitcher(this);
пожалуйста, обрати внимание на утекший this

все эти ситуации становятся возможны, тк действия по публикации/синхронизации значения происходят после конструктора

DataSourceContextUnsafe.databaseSwitcher = null
DataSourceContextUnsafe.databaseSwitcher = DatabseSwitcher без databaseNameSupplier
DataSourceContextUnsafe.databaseSwitcher = наполовину созданный объект