HH-221047 Add retries for kafka consumer
hhru/nuts-and-bolts pull request #538
Opened 2024-09-30 13:27 UTC by LMSBoris

2024-10-01 19:45 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
Хочется здесь оставить себе пространство для маневров, если вдруг ретраить будет не только через Kafka топики.

Давай сделаем вместо флага интерфейс и default реализацию для kafka топиков. Это пример, не конечная реализация

```java
interface Retrier {
  String sendTo()
  String recieveFrom();
}
```


++ 2 метода вместо одного

1) withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver) - для default-а aka ретраи через kafka

Что-то в стиле Retrier.kafkaSingleTopic() и Retrier.kafkaDefault()

2) withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, Retrier retrier) - для кастомных ретраеров

2024-10-01 19:45 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolverBuilder.java
> +public class RetryPolicyResolverBuilder<T> extends PredicateChainResolver<ConsumerRecord<String, T>, Throwable, RetryPolicy> {
Взамен этой реализации я предлагаю тебе сделать RetryPolicyResolver не классом, который создает политику, а классом, который выполняет ретрай от RetryPolicy.

Такой класс позволит не только контролировать retry политику,  но и делать дополнительные действия, которые часто бывают необходимы.

```java
abstract class RetryPolicyResolver<T> {
    protected Map<Exception, Runnable> exceptionHandlers;
    protected Map<T, Runnable> messageHandlers;

    void onException(Class<? extends Throwable> exceptionClass, Runnable action) // add exception handler
    void onMessage(T message, Runnable action) // add message handler
    boolean retry() // call all handlers prior to retryInternal
    abstract boolean retryInternal() // make call to a retry policy
}
```

2024-10-01 19:57 UTC, vbazhmin commented
Давай добъемся покрытия тестами всех требований от этой фичи. Накидаю сценариев

1. Все RetryPolicy следуют своим ограничениям и выполняют их
2. RetryPolicyResolver выполняет дополнительные сценарии для ошибок onException
3. RetryPolicyResolver выполняет дополнительные сценарии для сообщений onMessage
4. HeadersMessageMetadataProvider заполняется валидными данными после 3-х ретраев ( на каждом шаге : инициализация, сохранение, обновление )
5. Дополнительный retry Kafka Consumer корректно закрывается при закрытии основного
6. Дополнительный retry Kafka Consumer читает из нужного топика
7. RetryService пишет в нужный топик
8. withRetries корректно обновляет билдер и корректно содает новые consumer-ы

2024-10-02 11:49 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolver.java
> +  static <T> RetryPolicyResolverBuilder<T> builder(RetryPolicy defaultPolicy) {
ну ХЗ, а не станут ли разработчики тупить, когда под рукой нет готового ничего? ты в итоге будешь писать то же самое
```
(message, throwable) -> {
  if (throwable instanceof HibernateException) {
    return RetryPolicy.fixedDelay(Duration.ofSeconds(10));
  }
  return RetryPolicy.never();
}
```
вместо 
```
RetryPolicyResolver
  .builder(RetryPolicy.never())
  .onException(HibernateException.class, RetryPolicy.fixedDelay(Duration.ofSeconds(10)))
```

2024-10-02 11:49 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/policy/FixedDelay.java
> +public record FixedDelay(Duration delay) implements RetryPolicy {
мне казалось, что так понятнее, но :voobshe_vse_ravno:

2024-10-02 12:19 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolverBuilder.java
> +public class RetryPolicyResolverBuilder<T> extends PredicateChainResolver<ConsumerRecord<String, T>, Throwable, RetryPolicy> {
Тут очень много змеящихся темных смыслов. 
Политики - четкие иммутабельные штуки, которые на основании хистори говорят, когда ретраить и надо ли (и на них есть норм тесты). резолвер - способ выбрать политику на основании того, какое сообщение и с какой ошибкой упало. 
То, что ты предлагаешь - скорее расширенный RetryService (который мы всё пытаемся спрятать подальше от разрабов), потому что код "когда тебе сказали ретраить, сделай то-то" лежит именно там. Не вижу, почему эти доп. действия нельзя засунуть в ConsumeStrategy перед/после вызова Ack::retry.
Еще меньше понимаю, что делать, если надо ретраить сообщение Х по ошибке У. Вызвать и onMessage(X), и onException(Y)?
Можно в целом сделать в консумер билдере withRetryService, и им будут пользоваться примерно столько же, сколько и withAckProvider.

2024-10-02 12:25 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
ну про "не через кафку" можно просто сделать второй RetryService, но тут я призову на помощь @bokshitsky и сошлюсь на то, что уже есть АДР, и в нем ясно сказано "делаем через кафку". Если ты, конечно, не хочешь причинить добра всему интернету, у которого есть наш прекрасный опенсорсный наб и нет этих ужасных стесняющих АДР )

2024-10-03 06:52 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolver.java
> +  static <T> RetryPolicyResolverBuilder<T> builder(RetryPolicy defaultPolicy) {
https://docs.spring.io/spring-kafka/reference/kafka/annotation-error-handling.html

2024-10-03 06:54 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
RetryService должен быть один, ему не должно быть разницы как обрабатывать retry-и если поменялись места отправки и получения для сервиса ретраев

2024-10-03 07:03 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolverBuilder.java
> +public class RetryPolicyResolverBuilder<T> extends PredicateChainResolver<ConsumerRecord<String, T>, Throwable, RetryPolicy> {
> Политики - четкие иммутабельные штуки, которые на основании хистори говорят, когда ретраить и надо ли (и на них есть норм тесты). резолвер - способ выбрать политику на основании того, какое сообщение и с какой ошибкой упало.

Возможно, более правильным выбором было сделать RetryPolicy стратегией ретрая, а RetryPolicyResolver не "способ выбрать политику на основании того, какое сообщение и с какой ошибкой упало" а "способ выбрать политику на основании истории в метаданных".

> То, что ты предлагаешь - скорее расширенный RetryService (который мы всё пытаемся спрятать подальше от разрабов), потому что код "когда тебе сказали ретраить, сделай то-то" лежит именно там. 

Нет, ни в коем случае я это не предлагаю. RetryService и его шаги должны быть скрыты от разработчика и лишь возможность выбора !когда! (RetryPolictResolver)  и !как! (RetryPolicy)  ретраить открыты.

> Еще меньше понимаю, что делать, если надо ретраить сообщение Х по ошибке У. Вызвать и onMessage(X), и onException(Y)?

Хороший вопрос. В моем варианте это не продумано, получилась плохая абстракция. Посижу обдумаю варианты.

2024-10-03 08:50 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
1. receiveFrom у нас вообще не может быть, потому что в текущей реализации не мы поллим откуда-то ретрайные сообщения в RetryService, этим занимается retryConsumer. Соответственно, такой метод подразумевает, что надо выкинуть всю спринг-кафку и поллить самим из нативного клиента (или между retryConsumer и этим методом проложить какую-нибудь очередь в памяти, и даже думать об этом не хочу)
2. можно сделать что-то с интерфейсом "вот тебе сообщение, его нужно засунуть куда-то, чтобы оно ретраилось через 10 минут". Сейчас почти такой интерфейс у метода RetryService.retry(ConsumerRecord, Instant, MessageProcessingHistory). Если очень хочется, могу попробовать его вытащить из сервиса, но мы остаемся с той проблемой, что способ хранения метаданных в хедерах прибит гвоздями. А кто его просил прибить гвоздями, как не вы с Женей? У меня был MessageMetadataProvider, и доступ к метаданным делегировался ему, но вы сказали, что слишком много классов

2024-10-03 08:56 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolverBuilder.java
> +public class RetryPolicyResolverBuilder<T> extends PredicateChainResolver<ConsumerRecord<String, T>, Throwable, RetryPolicy> {
> Возможно, более правильным выбором было сделать RetryPolicy стратегией ретрая, а RetryPolicyResolver не "способ выбрать политику на основании того, какое сообщение и с какой ошибкой упало" а "способ выбрать политику на основании произвольных данных".

Ну предложи конкретный интерфейс для этих штук. Мы все равно упираемся в то, что нужна прокладка между 
`retry(message, throwable)` и `retry(ConsumerRecord, Instant, MessageProcessingHistory)`, а это и значит "на основании message и throwable принять решение, когда (и если)"  Я еще могу предложить сделать `Ack.retry(ConsumerRecord message, Object reason)` и дать волю людям использовать в качестве reason не только исключения, а энумы/строки/whatever, но от этого суть прокладки не сильно меняется

2024-10-03 14:25 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolver.java
> +  static <T> RetryPolicyResolverBuilder<T> builder(RetryPolicy defaultPolicy) {
Договорились, что убираю RetryPolicyResolverBuilder, без него жизнь разраба не станет сильно сложнее, а кода будет меньше

2024-10-03 14:29 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/policy/FixedDelay.java
> +public record FixedDelay(Duration delay) implements RetryPolicy {
Там рядом, как я вспомнил, есть такой же базовый Progressive, который вроде как должен противопоставляться FixedDelay. Кажется, что надо как-то синхронно менять эти два названия. Может, просто Fixed?

2024-10-03 14:31 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
решили, что здесь не принципиально что-то делать. Посмотрю, может, удастся собрать топик и продюсер в KafkaRetrier, который пока будет единственной реализацией Retrier

2024-10-03 14:33 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/RetryPolicyResolverBuilder.java
> +public class RetryPolicyResolverBuilder<T> extends PredicateChainResolver<ConsumerRecord<String, T>, Throwable, RetryPolicy> {
Сошлись на том, что, пока не видно хорошей альтернативы, ничего не делаем

2024-10-17 16:05 UTC, LMSBoris commented
Посмотрел внимательнее. Сценарии почти все покрыты
1. [RetryPolicyTest](https://github.com/hhru/nuts-and-bolts/blob/c24691d0950ad82d72d729d2ef6330c460e02a7b/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/retry/policy/RetryPolicyTest.java)
2. То, что резолвер [выдает разные policy для разных exception](https://github.com/hhru/nuts-and-bolts/blob/ab483ec410967719a9aeb9fb1b9b06f987bea87c/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/RetryServiceTest.java#L96-L105) 
3. То, что резолвер [выдает разные policy для разных message](https://github.com/hhru/nuts-and-bolts/blob/ab483ec410967719a9aeb9fb1b9b06f987bea87c/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/RetryServiceTest.java#L107-L116)
4. Хистори и nextRetryTime [проходят конвертацию в хедера и обратно без изменений](https://github.com/hhru/nuts-and-bolts/blob/ab483ec410967719a9aeb9fb1b9b06f987bea87c/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/retry/HeadersMessageMetadataProviderTest.java), выставляются корректно при [первом](https://github.com/hhru/nuts-and-bolts/blob/ab483ec410967719a9aeb9fb1b9b06f987bea87c/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/RetryServiceTest.java#L47-L61) и [втором](https://github.com/hhru/nuts-and-bolts/blob/ab483ec410967719a9aeb9fb1b9b06f987bea87c/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/RetryServiceTest.java#L47-L81) ретраях
5. ТУДУ + сейчас код заведомо написан неправильно
6. ТУДУ
7. RetryService передает в продюсера [правильный топик](https://github.com/hhru/nuts-and-bolts/blob/ab483ec410967719a9aeb9fb1b9b06f987bea87c/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/RetryServiceTest.java#L56)
8. ТУДУ
9. [Такой код](https://github.com/hhru/nuts-and-bolts/blob/c24691d0950ad82d72d729d2ef6330c460e02a7b/nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/InMemorySeekOnlyAck.java#L38) тестировать? Кажется избыточным
10. ТУДУ тестировать довольно неудобно, но попробую

2024-10-24 06:36 UTC, vbazhmin commented on nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/DefaultConsumerBuilderTest.java
> +  void withRetries() {
Возможно, стоило бы проверить, что мы умеем корректно создавать consumer с ретрай механизмом

2024-10-24 07:06 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
@bokshitsky Женя, я хочу сделать по-умолчанию retry, которые не будут взаимодействовать с retry service, а будут напрямую сами себе слать сообщение в retry_receive топик. Есть возражения ?

В любом выборе придется создать метод, который станет выбором по-умолчанию. В моем предложении - useSingleRetryTopic будет true.

```java
ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver);
```

2024-10-24 07:29 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +   * Enable retries for this consumer.
Достаточно сложное описание, которое содержит много деталей реализации, давай попробуем сделать его легче ?

Попробовал переформулировать. Что думаешь ?

```
   * Configures kafka consumer for retries via {@link Ack#retry(ConsumerRecord, Throwable)}
   * <p>
   * Requirements : {@link ConsumeStrategy} MUST BE thread safe
   * <p>
   * Messages scheduled for retries are stored in a separate kafka topic.
   * <p>
   * If useSingleRetryTopic is false then topic is <i>topicName_operationName_retry_send</i>.
   * In this case another service is responsible for scheduling next retry by sending message to <i>topicName_operationName_retry_recieve</i>.
   * <p>
   * If useSingleRetryTopic is true then topic is <i>topicName_operationName_retry_recieve</i>.
   * In this case service itself is responsible for scheduling retries.
   * <p>
   * In either case later retry messages will be read by a DIFFERENT kafka consumer and processed with the same {@link ConsumeStrategy}.
```

2024-10-24 07:30 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +   * Enable retries for this consumer.
Про headers думаю стоит написать около метода, который его возвращает, чтобы было понятнее зачем он нужен

2024-10-24 07:31 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +   * Enable retries for this consumer.
Про выбор политики ретраев думаю стоит написать на самих политиках для каких целей они лучше всего подходят

2024-10-24 08:38 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +   * Enable retries for this consumer.
Документация - наше всё. Непременно учту, предложения отличные

2024-10-24 08:42 UTC, LMSBoris commented
@vbazhmin Тему с юнитами закрываем?

2024-10-24 12:18 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/retry/policy/FixedDelay.java
> +public record FixedDelay(Duration delay) implements RetryPolicy {
почему бы и нет, согласен

2024-10-24 12:27 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
> +   * Time of retry is determined based on message itself, its {@link MessageProcessingHistory} and processing error details (if any).
Напиши, пожалуйста, описание для класса истории с примером структуры, которая будет сохраняться в топик. Здесь она скорее вредна, разработчик хочет поретраить не углубляясь в детали реализации.

2024-10-24 12:31 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
> +   * Implementation MAY move offsets to next after that message when (and if) it has been successfully scheduled for retry.
`MAY`, разве мы не всегда двигаем оффсет дальше, когда успешно поретраили сообщение ?

2024-10-24 12:33 UTC, vbazhmin commented
> @vbazhmin Тему с юнитами закрываем?

Да, кажется покрыли все что нужно

2024-10-24 12:45 UTC, vbazhmin commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
Давай еще кейс добавим, когда ретраим несколько раз сообщение

2024-10-24 13:00 UTC, vbazhmin commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
И еще тест кейс на то, что мы ретраим несколько сообщений под ряд

2024-10-24 13:01 UTC, LMSBoris commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
Надеюсь, трёх раз хватит ) Сделаем

2024-10-24 13:03 UTC, vbazhmin commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
и еще один, когда будет ошибка десериализации сообщения

2024-10-24 14:57 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
> +   * Implementation MAY move offsets to next after that message when (and if) it has been successfully scheduled for retry.
что-то мне кажется на это стоит тоже функциональный тест написать в nab-tests, что если сообщение ушло в ретрай, то мы его не ждем и дальше процессим сообщения

2024-10-24 15:38 UTC, LMSBoris commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
уже говорили, так не работает пока что. Это вылетает выше, чем мы ретраим, на уровне спринг-кафки

2024-10-24 17:17 UTC, vbazhmin commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
точно, спасибо

2024-10-25 06:35 UTC, bokshitsky commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
> +   * Caller MAY use returned Future but is not required to wait for it to complete because next call to {@link #seek(ConsumerRecord)}
CompletableFuture вроде сама по себе позволяет если что делать onSuccess, onException?

2024-10-25 06:36 UTC, bokshitsky commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumeStrategy.java
> +          ack.retry(record, e);
retry же вернет ошибку, если он не настроен?
правильно ли здесь его по дефолту писать - это ведь сломает консумеры, которые без ретрая живут и работают.

2024-10-25 08:29 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
> +   * Caller MAY use returned Future but is not required to wait for it to complete because next call to {@link #seek(ConsumerRecord)}
Позволяет, только не в том же потоке, что и произошел retry

2024-10-26 20:36 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumeStrategy.java
> +          ack.retry(record, e);
по-моему мы обговаривали, что нужна политика по-умолчанию - не ретраить

2024-10-26 20:42 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumeStrategy.java
> +          ack.retry(record, e);
вот тут https://github.com/hhru/nuts-and-bolts/pull/538/files#diff-9e00459a5c310adbb46f4a0c3db28d9ae2158ac0bef53748e4d8deb3396e3ae9R48  вместо ошибки можно залогировать под WARNING мол вы не ретраите

2024-10-26 20:42 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
FTR : обсдудили устно, так и сделаем

2024-10-28 08:42 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
> +   * Caller MAY use returned Future but is not required to wait for it to complete because next call to {@link #seek(ConsumerRecord)}
ну кстати фьюча никак не заставляет её ждать, и об этом я ясно написал в документации. ты можешь на неё что-то повесить, но не обязан это делать.

2024-10-28 08:45 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumeStrategy.java
> +          ack.retry(record, e);
Мы обговаривали, что no-op с большой вероятностью сломает голову людям, которые будут дергать ретрай, не получать ошибок и думать, что всё хорошо (когда на самом деле нет). В симпл консумере сделано так, чтобы поведение не изменилось - если у тебя вылетела непойманная ошибка, ты откатываешь батч.

2024-10-28 11:15 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/Ack.java
> +   * Implementation MAY move offsets to next after that message when (and if) it has been successfully scheduled for retry.
Ну [тут](https://github.com/hhru/nuts-and-bolts/blob/6505b0c86b83dc23e4fe328cf87dbb9bbc10a451/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/KafkaInternalTopicAckTest.java#L78-L90) проверяется, что ретрайная фьюча на выходе из retry() еще в пути, а после всяких сиков/аков уже приехала.

А [тут](https://github.com/hhru/nuts-and-bolts/blob/6505b0c86b83dc23e4fe328cf87dbb9bbc10a451/nab-kafka/src/test/java/ru/hh/nab/kafka/consumer/KafkaInternalTopicAckTest.java#L100) - что seek() и правда двигает оффсеты для ретрайных, которых дождался

2024-10-28 14:32 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  ConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, boolean useSingleRetryTopic);
Сейчас я сделал явное указание топиков, посмотрите внимательно, пока еще не поздно вернуть обратно. Разумеется, сделать single-topic по дефолту тоже можно

2024-10-29 10:44 UTC, LMSBoris commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
сделал [тест на 3 ретрая](https://github.com/hhru/nuts-and-bolts/blob/0c1a745e2f57f5d6c6231a700722cb820d7ec20b/nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java#L66-L77)

2024-10-29 11:21 UTC, LMSBoris commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java
> +  void retryOnceUsingSingleTopic() throws InterruptedException {
а вот и тест [на три сообщения подряд](https://github.com/hhru/nuts-and-bolts/blob/5da7cda13521d945a215977f9b3249a8c00621f9/nab-tests/src/test/java/ru/hh/nab/kafka/consumer/ConsumerRetriesTest.java#L77-L93)

2024-10-29 17:34 UTC, vbazhmin approved these changes

2024-10-30 20:27 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/DefaultConsumerBuilder.java
> +  public DefaultConsumerBuilder<T> withRetries(KafkaProducer retryProducer, RetryPolicyResolver<T> retryPolicyResolver, RetryTopics retryTopics) {
Зачем заменять конкретной реализацией `DefaultConsumerBuilder` ? Вроде было гибче с интерфейсом

2024-10-30 20:36 UTC, vbazhmin approved these changes

2024-10-31 08:28 UTC, LMSBoris commented
Убрал пару мест, где автоформатирование сделало лишние строки

2024-10-31 08:32 UTC, LMSBoris commented
Досквашил, -1 коммит

2024-11-01 11:21 UTC, vbazhmin approved these changes

2024-11-11 15:21 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/SimpleKafkaConsumer.java
> +public abstract class SimpleKafkaConsumer<M> implements MessageProcessor<M>, SmartLifecycleContainer, InitializingBean {
TLDR : Этот класс начал приносить страдания. Предлагаю удалить его и в релиз нотах рекомендовать переехать на KafkaConsumerFactory с ConsumeStrategy.

Reason : Класс повторяет уже существующие абстракции. Создание объектов уже есть в KafkaConsumerFactory. Отложенный старт разработчик в состоянии реализовать сам, мы не должны решать за него когда запускать kafka consumer. 

На этом комменте буду настаивать, потому что реализация из-за него начинает гнить. Пример `SmartLifecycleContainer`.

2024-11-11 15:21 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/util/SmartLifecycleContainer.java
> +public interface SmartLifecycleContainer extends SmartLifecycle {
См. комментарии к `SimpleKafkaConsumer`

2024-11-11 15:21 UTC, vbazhmin commented on nab-tests/src/test/java/ru/hh/nab/kafka/consumer/SimpleKafkaConsumerTest.java
> +class SimpleKafkaConsumerTest extends KafkaConsumerTestbase {
Продолжу смотреть после удаления SimpleKafkaConsumer

2024-11-11 15:22 UTC, vbazhmin requested changes
Requesting changes

2024-11-11 15:42 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  default KafkaConsumer<T> start() {
ну это для тех, у кого написано `factory.builder(topic, messageClass).start()`. Теперь я вместо этого предлагаю использовать `factory.builder(topic, messageClass).build().start()`. Так можно убрать ограничение "консумер стартует сразу в конструкторе". Но я просто не придумал более внятного способа это сделать.

2024-11-11 15:44 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
> +  private boolean readingAllPartitions() {
но ведь в билдере ConsumerBuilder::withAllPartitionsAssigned

2024-11-14 14:55 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/SimpleKafkaConsumer.java
> +public abstract class SimpleKafkaConsumer<M> implements MessageProcessor<M>, SmartLifecycleContainer, InitializingBean {
Таки да, я удалил его и нашел неплохой способ без него обойтись в конечном сервисе.

2024-11-14 14:56 UTC, LMSBoris commented
Готово, пора смотреть

2024-11-14 14:57 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  default KafkaConsumer<T> start() {
Если прям настаиваешь, могу и убрать, но кажется, мы ничего не портим, оставляя разработчику возможность стартовать консумер в один вызов метода вместо двух

2024-11-14 15:58 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
> +  private boolean readingAllPartitions() {
похоже подумаем потом как привести к общей терминологии

2024-11-14 15:59 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  default KafkaConsumer<T> start() {
настаиваю

2024-11-15 09:19 UTC, LMSBoris commented
Удалил, нажми пожалуйста кнопочку )

2024-11-15 09:46 UTC, LMSBoris commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/ConsumerBuilder.java
> +  default KafkaConsumer<T> start() {
убрал

2024-11-15 11:44 UTC, vbazhmin approved these changes

2024-11-15 15:55 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
>      this.logger = logger;
Забыл про логгер

```java
if (logger == null) {
      logger = LoggerFactory.getLogger(getClass());
    }
```

2024-11-15 15:58 UTC, vbazhmin commented on nab-kafka/src/main/java/ru/hh/nab/kafka/consumer/KafkaConsumer.java
> +      if (logger != null) {
Думаю можно удалить логирование в start/stop, если его может и не быть

2024-11-18 12:17 UTC, vbazhmin approved these changes

2024-11-18 13:59 UTC, LMSBoris commented
NoopKafkaConsumer немножко обломал идиллию. Убрал/перенес чеки, с которыми ему не работалось

2024-11-18 16:39 UTC, merged