HH-233707 remove error log in SentryFilter
hhru/nuts-and-bolts pull request #543
Opened 2024-10-11 17:11 UTC by rogoza-igor

> [!IMPORTANT] 
> Добавь в описание PR changelog в формате:

- [ ] **version change** : PATCH
- [ ] **description**: удалено логирование ошибки в SentryFilter
- [ ] **requires_changes_in_hh** : false
- [ ] **instructions** :

2024-10-11 17:27 UTC, doc-sheet approved these changes

2024-10-11 19:42 UTC, Powerrr approved these changes

2024-10-14 08:06 UTC, heruv1m commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
> +          // do nothing if requestId is not valid uuid
лучше дебаг

2024-10-14 08:07 UTC, heruv1m requested changes
ю

2024-10-14 08:10 UTC, pvorlov commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
Если кривые риды всё равно не работают может вместо них использовать телеметрийный traceID?

2024-10-14 08:36 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
У нас телеметрийный модуль живет отдельно, и в теории он не обязан быть подключенным

2024-10-14 08:38 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
> +          // do nothing if requestId is not valid uuid
поправил

2024-10-14 09:08 UTC, pvorlov commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
Ну можно ввести понятие TraceId не привязанное к телеметрии а сделать его частью корного функционала.
Вобщем если сейчас дорого - хочу задачу и TODO-шку

2024-10-14 09:13 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
https://jira.hh.ru/browse/PORTFOLIO-19764

2024-10-14 09:14 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
тудушку добавил

2024-10-14 09:23 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
> Заголовок еще один достать почти бесплатно

не понял, о каком заголовке речь

> А если понятный формат чего не хватает для сентри, то может проверку сделать до того как сетить?

сентри [хочет](https://github.com/getsentry/sentry-java/blob/2ab34ebca967b5bdac6e49a3b12f4b7e982b72be/sentry/src/main/java/io/sentry/protocol/SentryId.java#L52-L71) валидный uuid, в жавке внезапно нет какого то утилитного метода для валидации uuid'а, который бы вернул true или false. Можем, к примеру, с помощью регулярок валидировать, но чет не хочется

2024-10-14 09:29 UTC, heruv1m commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
заголовок https://github.com/hhru/nuts-and-bolts/blob/master/nab-telemetry/src/main/java/ru/hh/nab/telemetry/IdGeneratorImpl.java#L52

2024-10-14 09:30 UTC, heruv1m commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
а где стреляет?
тут https://github.com/getsentry/sentry-java/blob/2ab34ebca967b5bdac6e49a3b12f4b7e982b72be/sentry/src/main/java/io/sentry/protocol/SentryId.java#L64

2024-10-14 09:35 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
> а где стреляет?

[отсюда](https://github.com/getsentry/sentry-java/blob/2ab34ebca967b5bdac6e49a3b12f4b7e982b72be/sentry/src/main/java/io/sentry/protocol/SentryId.java#L70) тоже вылетит IllegalArgumentException, если uid невалидный

2024-10-14 09:38 UTC, heruv1m commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
я скорее про то, что ты сейчас логи видел. Наверняка там есть какой паттерн. Например чаще всего длинные айдишники приходят

2024-10-14 09:38 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
> заголовок https://github.com/hhru/nuts-and-bolts/blob/master/nab-telemetry/src/main/java/ru/hh/nab/telemetry/IdGeneratorImpl.java#L52

не понимаю, что именно предлагаешь) в SentryFilter щас этот заголовок и достаем. Хорошо бы этот rid доставать где то централизованно и генерить ранздомный, если rid невалидный / его вообще нет. Но это можно сделать отдельно в рамках портфеля, который выше скинул

2024-10-14 09:47 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
> я скорее про то, что ты сейчас логи видел

Вот такого плана видел rid'ы - `ws_session_check_1a5d986b-628c-4ef3-a46b-042e5f9e728e_1`. Ну и исключение вылетало из той строчки, которую ты скинул

2024-10-14 09:49 UTC, pvorlov commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
Ну ты поставь TODO лучше напротив debug с текстом что вообще говоря debug плохо и надо вернуть warn/error как выйдет PORTFOLIO-19764.

А иначе не понятно к чему тудушка

2024-10-14 10:21 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
Данная тудушка не связана с уровнем debug. Она про централизованное получение traceId для сентри и телеметрии. Завел [отдельную](https://jira.hh.ru/browse/HH-233805) задачу под это и связал ее с PORTFOLIO-19764

Хочешь напротив debug еще одну тудушку?

2024-10-14 10:33 UTC, heruv1m approved these changes

2024-10-14 10:39 UTC, pvorlov commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
Ну как же не связана?
Если у нас будет прокидываться traceid то он будет корректным uuid и количество ошибок существенно сократится.
А если нет, это уже что-то не здоровое и писать warn/error уже становится нормально

2024-10-14 10:58 UTC, rogoza-igor commented on nab-starter/src/main/java/ru/hh/nab/starter/filters/SentryFilter.java
>            scope.getPropagationContext().setTraceId(new SentryId(requestId));
добавил

2024-10-14 14:17 UTC, pvorlov approved these changes

2024-10-14 14:57 UTC, merged